CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Cars" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "VinCode" text NULL,
    "Brand" character varying(100) NOT NULL,
    "Model" text NULL,
    "Year" integer NOT NULL,
    "Price" numeric NOT NULL,
    "Color" text NULL,
    "ProductionDate" timestamp without time zone NOT NULL DEFAULT (now()),
    "Status" integer NOT NULL,
    "RegisteredAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Cars" PRIMARY KEY ("Id")
);

CREATE TABLE "Customers" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FullName" text NULL,
    "Document" text NULL,
    "BirthDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

CREATE TABLE "Orders" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "IdCar" integer NOT NULL,
    "IdCustomer" integer NOT NULL,
    "TotalCost" numeric NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Cars_IdCar" FOREIGN KEY ("IdCar") REFERENCES "Cars" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_Customers_IdCustomer" FOREIGN KEY ("IdCustomer") REFERENCES "Customers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ExtraOrderItems" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NULL,
    "Price" numeric NOT NULL,
    "IdOrder" integer NOT NULL,
    CONSTRAINT "PK_ExtraOrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExtraOrderItems_Orders_IdOrder" FOREIGN KEY ("IdOrder") REFERENCES "Orders" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_ExtraOrderItems_IdOrder" ON "ExtraOrderItems" ("IdOrder");

CREATE UNIQUE INDEX "IX_Orders_IdCar" ON "Orders" ("IdCar");

CREATE INDEX "IX_Orders_IdCustomer" ON "Orders" ("IdCustomer");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210428134431_InitialMigration', '5.0.5');

COMMIT;

